#include "../headers/TRI_Main.h"
#include "../headers/TRI_Tools.h"
#include "../headers/rootalias.h"

#include "../headers/cuts.h"
#include "../headers/corrections.h"
#include "../classes/yieldHistogram.h"
#include "../classes/yieldHistogram.cpp"

#include "emc.cpp"
#include "emcR.cpp"
#include "kin_clean.cpp"
#include "merge_all.cpp"
#include "kinYield.cpp"
#include "apply_rc.cpp"
#include "ind_cor.cpp"
#include "kin_clean_new.cpp"
#include "merge_all_new.cpp"
#include "apply_rc_new.cpp"
#include "ev_scan.C"
#include "iso_apply.cpp"
#include "whitlow_emc.C"
